app = "spotify-banger"
kill_signal = "SIGINT"
kill_timeout = 5

[deploy]
strategy = "bluegreen"

[env]
BIND = "0.0.0.0:8080"
SPOTIFY_CLIENT_ID = "be6201c1e3154c51b50ffb302e770db5"

[[services]]
internal_port = 8080
protocol = "tcp"

[services.concurrency]
hard_limit = 500
soft_limit = 450

[[services.http_checks]]
grace_period = "5s"
interval = "10s"
method = "get"
path = "/api/healthy"
protocol = "http"
restart_limit = 0
timeout = "2s"
tls_skip_verify = false

[[services.ports]]
force_https = true
handlers = []
port = 80

[[services.ports]]
handlers = ["tls"]
port = 443

[[services.tcp_checks]]
grace_period = "1s"
interval = "15s"
restart_limit = 0
timeout = "2s"
