on:
    push:
        branches:
            - main

name: Dioxus

jobs:
    clippy:
        runs-on: ubuntu-latest
        steps:
            - name: Stable Rust with clippy
              uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: stable
                  components: clippy
                  target: wasm32-unknown-unknown

            - uses: actions/checkout@v2

            - name: Annotate commit with clippy warnings
              uses: actions-rs/clippy-check@v1
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  args: --all-features --all-targets

    fmt:
        runs-on: ubuntu-latest
        steps:
            - name: Stable Rust with rustfmt
              uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: stable
                  components: rustfmt

            - uses: actions/checkout@v2

            - name: Check formatting
              uses: actions-rs/cargo@v1
              with:
                  command: fmt
                  args: --check

    deploy:
        needs: clippy
        runs-on: ubuntu-latest
        env:
            TRUNK_VERSION: "v0.16.0"
        steps:
            - name: Stable Rust
              uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: stable
                  target: wasm32-unknown-unknown

            - uses: actions/checkout@v2

            - name: Create Sentry release
              uses: getsentry/action-release@v1
              env:
                  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
                  SENTRY_ORG: dusterthefirst
                  SENTRY_PROJECT: spotify-banger
              with:
                  environment: production

            - name: Install trunk
              run: wget -qO- "https://github.com/thedodd/trunk/releases/download/${TRUNK_VERSION}/trunk-x86_64-unknown-linux-gnu.tar.gz" | tar -xzf-

            - name: Build
              run: ./trunk build --release
              env:
                SENTRY_RELEASE: ${{ github.sha }}

            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@v4.2.5
              with:
                  branch: deploy
                  folder: dist
